config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  post '/api', to: 'api_keys#create'
  delete '/api', to: 'api_keys#destroy'
  get '/api', to: 'api_keys#index'

  get '/api/user', to: 'api_keys#user_details'
  get '/api/time_slots', to: 'api_keys#time_slots'
  get '/api/meetings', to: 'api_keys#meetings'
  get '/api/meeting', to: 'api_keys#meeting'


  resources :meetings, only: [:index, :show, :new, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :slots
  root to: 'main#index'

  get 'meeting/searchDate', to: 'meetings#searchDate', as: :search_date
  # GET /about
  get 'about', to: 'about#index'

  get 'profile', to: 'profiles#edit', as: :edit_profile
  patch 'profile', to: 'profiles#update'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  # get 'user/photos', to: 'photos#index'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :user
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_slot, only: %i[ show edit update destroy ]

  # GET /slots or /slots.json
  def index
     @slots = Slot.where(user_id: Current.user.id)
  end

  # GET /slots/1 or /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots or /slots.json
  def create
    @slot = Slot.new(slot_params)
    @slot.user_id = Current.user.id

    respond_to do |format|
      if @slot.save
        format.html { redirect_to slot_url(@slot), notice: "Slot was successfully created." }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1 or /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to slot_url(@slot), notice: "Slot was successfully updated." }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1 or /slots/1.json
  def destroy
    @slot.destroy

    respond_to do |format|
      format.html { redirect_to slots_url, notice: "Slot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def slot_params
      params.require(:slot).permit(:start_time, :user_id)
    end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_with(model: slot) do |form| %>
  <% if slot.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
        <% slot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :start_time, class: "form-label" %>
    <%#= form.datetime_field :start_time %>
    <%= form.datetime_select :start_time,  minute_step: 30, start_hour: 8, end_hour: 22, class: "form-control"  %>
  </div>

  <div>
    <%#= form.label :user_id, style: "display: block" %>
    <%#= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit 'Create a Slot', :class => 'btn btn-secondary' %>
  </div>
<% end %>

app/views/slots/_slot.html.erb
<div id="<%= dom_id slot %>">
      <h5 class="card-title">Date: <%= slot.start_time.strftime("%m/%d/%Y") %></h5>
      <p class="card-text">Time: <%= slot.start_time.strftime("%I:%M%p") %></p>
</div>

app/views/slots/edit.html.erb
<h1>Editing slot</h1>

<%= render "form", slot: @slot %>

<br>

<div>
  <%= link_to "Show this slot", @slot %> |
  <%= link_to "Back to slots", slots_path %>
</div>

app/views/slots/index.html.erb
<% if notice.present? %>
  <!--  <div class="alert alert-info"><%#= notice %></div>-->
<% end %>

<h1>When are you planning to study?</h1>
<ol>
  <li class="text-muted">First, you have to specify your intention of when you what to study. You can do that by creating a study time slot.</li>
  <li class="text-muted">After that you can click the details link of the time-slots to either edit it of scan for a possible match.</li>
</ol>
<%= link_to "New slot", new_slot_path, class: "btn btn-secondary mx-1 my-3" %>

<div id="slots" class="d-flex flex-row flex-wrap">
  <% @slots.each do |slot| %>
    <div class="card mx-1 my-1" style="width: 18rem;">
      <div class="card-body">
        <%= render slot %>
        <%= link_to "Show this slot", slot, class: "card-link link-secondary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/slots/new.html.erb
<h1 >Enter the timings here</h1>
<div class="my-4">
  <%= render "form", slot: @slot %>
</div>


<br>

<div>
  <%= link_to "Back to slots", slots_path, class: "link-secondary"  %>
</div>

app/views/slots/show.html.erb
<% if notice.present? %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>
<div class="card my-5">
  <div class="card-body">
    <% if Current.user %>
      <%= render @slot %>
      <div class="mt-2">
        <%= link_to "Edit this slot", edit_slot_path(@slot), class: "link-secondary"  %> |
        <%= link_to "Back to slots", slots_path, class: "link-secondary" %>

        <%= button_to "Destroy this slot", @slot, method: :delete, class: "btn btn-danger my-2" %>
      </div>


    <% end %>
  </div>
</div>
<div>
  <%= link_to "Search a date for this time slot", new_meeting_path(time_slot: params[:id]), class: "btn btn-success"  %>
</div>