config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  post '/api', to: 'api_keys#create'
  delete '/api', to: 'api_keys#destroy'
  get '/api', to: 'api_keys#index'

  get '/api/user', to: 'api_keys#user_details'
  get '/api/time_slots', to: 'api_keys#time_slots'
  get '/api/meetings', to: 'api_keys#meetings'
  get '/api/meeting', to: 'api_keys#meeting'


  resources :meetings, only: [:index, :show, :new, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :slots
  root to: 'main#index'

  get 'meeting/searchDate', to: 'meetings#searchDate', as: :search_date
  # GET /about
  get 'about', to: 'about#index'

  get 'profile', to: 'profiles#edit', as: :edit_profile
  patch 'profile', to: 'profiles#update'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  # get 'user/photos', to: 'photos#index'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :first_user, class_name: 'User'
  belongs_to :second_user, class_name: 'User'
  has_many :messages, dependent: :destroy
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.where(first_user_id: Current.user.id).or(Meeting.where(second_user_id: Current.user.id))
  end

  def searchDate
    @meeting = Meeting.new
    @meeting_second_user = nil
    @start_time = params[:start_time]
    @first_user = params[:first_user]

    # An variable to store all the user_id of user available during @start_time
    @possible_matches = Slot.where(start_time: @start_time).where.not(user_id: @first_user)
    # @possible_matches = Slot.where(start_time: @start_time).or(Slot.where.not(user_id: @first_user))

    if @possible_matches.present?

      # An array to store user info from User table correlating to User_id in the @possible match
      @matches = Array.new

      # Check if the logged-in user already has a meeting at this time
      # An array containing all the meeting of the logged-in user
      @all_meetings = Meeting.where(first_user_id: Current.user.id).or(Meeting.where(second_user_id: Current.user.id))

      @errors_array = Array.new

      @possible_matches.each do |match|
        @all_meetings.each do |meet|
          if match.start_time == @start_time
            @errors_array.push("You already have a meeting at this time")
            if (match.user_id == meet.first_user_id) || (match.user_id == meet.second_user_id)
              @errors_array.push("You already have a meeting at this time with this person")

            end

          end
        end
      end

      if @errors_array.nil?
      else
        if @errors_array[1] == "You already have a meeting at this time"
          @errors_array.each do |err|
            flash[:notice] = err
          end
          redirect_to slots_path
        end
      end

      @all_meetings.each do |meets|
        if meets.starts_at == @start_time
          @redirect_error = "You already have a meeting at this time."
        end
      end
      @possible_matches.each do |slot_match|
        @matches << User.select(:id, :first_name, :last_name, :details).find_by(id: slot_match.user_id)
      end
    else

      redirect_to slots_path, notice: "Sorry, No match available for this time"
      # format.html { render :new, status: :unprocessable_entity }

    end

  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    @slot_id = params[:time_slot]
    time_slot = Slot.find(@slot_id)
    @meeting_starts_at = time_slot.start_time
    @meeting_ends_at = (@meeting_starts_at.to_datetime + 1.hours).to_s
    @meeting_first_user = time_slot.user_id
    @meeting_first_user_name = User.find(@meeting_first_user).first_name
  end

  # # GET /meetings/1/edit
  # def edit
  # end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:starts_at, :ends_at, :first_user_id, :second_user_id)
    end


end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!--  <div>-->
    <%#= form.label :starts_at, style: "display: block"%>
    <%#= form.hidden_field :starts_at, value: @meeting_starts_at %>
    <%#= form.datetime_field :starts_at %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :ends_at, style: "display: block" %>
    <%#= form.hidden_field :ends_at, value: @meeting_ends_at %>
    <%#= form.datetime_field :ends_at %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :first_user_id, style: "display: block" %>
    <%#= form.text_field :first_user_id %>
    <%#= form.hidden_field :first_user_id, value: @meeting_first_user %>

<!--  </div>-->

<!--  <div>-->
    <%#= form.label :second_user_id, style: "display: block" %>
    <%#= form.text_field :second_user_id %>
    <%#= form.hidden_field :second_user_id, value: @meeting_second_user %>

<!--  </div>-->

  <div>
    <%= form.submit "Set up a meeting with <this> person"%>
  </div>
<% end %>

app/views/meetings/_matchbutton.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--  <div>-->
  <%#= form.label :starts_at, style: "display: block"%>
  <%#= form.hidden_field :starts_at, value: @meeting_starts_at %>
  <%#= form.datetime_field :starts_at %>
  <%= hidden_field_tag 'starts_at', @starts_at %>
  <!--  </div>-->

  <!--  <div>-->
  <%#= form.label :ends_at, style: "display: block" %>
  <%#= form.hidden_field :ends_at, value: @meeting_ends_at %>
  <%#= form.datetime_field :ends_at %>
  <%= hidden_field_tag 'ends_at', @ends_at %>

  <!--  </div>-->

  <!--  <div>-->
  <%#= form.label :first_user_id, style: "display: block" %>
  <%#= form.text_field :first_user_id %>
  <%#= form.hidden_field :first_user_id, value: @meeting_first_user %>
  <%= hidden_field_tag 'first_user_id', @first_user_id %>


  <!--  </div>-->

  <!--  <div>-->
  <%#= form.label :second_user_id, style: "display: block" %>
  <%#= form.text_field :second_user_id %>
  <%#= form.hidden_field :second_user_id, value: @meeting_second_user %>
  <%= hidden_field_tag 'second_user_id', @second_user_id %>


  <!--  </div>-->

  <div>
    <%= form.submit "Set up a meeting with <this> person"%>
    <% byebug %>
  </div>
<% end %>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>" class="pt-3">
  <p class="">
    <strong>Date: </strong>
    <%= meeting.starts_at.strftime("%A %b %d, %Y")  %>
  </p>

  <p class="">
    <strong>Starting Time: </strong>
    <%= meeting.starts_at.strftime("%I:%M %p")  %>
  </p>

  <p class="">
    <strong>Ending Time: </strong>
    <%= meeting.ends_at.strftime("%I:%M %p")  %>
  </p>

  <p>
    <strong>First Attendant:</strong>
    <%= meeting.first_user.first_name %> <%= meeting.first_user.last_name %>
  </p>

  <p>
    <strong>Second Attendant:</strong>
    <%= meeting.second_user.first_name %> <%= meeting.second_user.last_name %>
  </p>

</div>

app/views/meetings/index.html.erb
<% if notice.present? %>
    <div class="alert alert-info"><%= notice %></div>
<% end %>

<h1>Meetings</h1>
<% if @meetings.empty? %>
  <p>You don't have any upcoming meetings.</p>
<% else %>
  <p class="text-muted">Here are the list of your past and future meetings.</p>
  <p class="text-muted">You can Chat with your buddy or destroy the meeting by clicking on 'the Show this meeting button'</p>
  <div id="meetings" class="d-flex flex-row flex-wrap">
    <% @meetings.each do |meeting| %>
      <div class="card mx-1 my-1" style="width: 18rem;">
        <div class="card-body">
          <%= render meeting %>
          <p>
            <%= link_to "Show this meeting", meeting, class: "card-link link-secondary"  %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/meetings/new.html.erb
<h1 class="my-1">Confirm Meeting Details</h1>

<p class="mt-4">If a match is found, your meeting details will be:   </p>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Date: <%= @meeting_starts_at.strftime("%m/%d/%Y, %A") %></h5>
    <h6 class="card-text text-muted">Starts at: <%= @meeting_starts_at.strftime("%I:%M %p") %></h6>
    <p class="card-text">Duration: 1 hr</p>
    <%= link_to "Search for a match", search_date_path(start_time: @meeting_starts_at, first_user: @meeting_first_user), method: :get, class: "btn btn-success"  %>
  </div>
</div>


<br>

<div>
  <%= link_to "Back to slots", slots_path, class: "card-link link-secondary"  %>
</div>

app/views/meetings/searchDate.html.erb
<% if notice.present? %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<h1>Search Result</h1>

<% if @matches.present? %>
  <h2>Parameters:</h2>
  <div id="meetings">
    <p>
      <strong>Meeting will starts at:</strong>
      <%= @start_time %>
    </p>

    <p>
      <strong>Duration: 1hr</strong>
      <%#= @ends_time %>
    </p>
    <h2>Matches:</h2>

    <div class="d-flex flex-row flex-wrap">
      <% @matches.each do |match| %>
        <div class="card mx-1 my-1" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= match.first_name %> <%= match.last_name %></h5>
            <h6 class="card-text text-muted"><%= match.details %></h6>

            <%= form_for @meeting do |form| %>
              <%= form.hidden_field :starts_at, value: params[:start_time] %>
              <%= form.hidden_field :ends_at, value: (params[:start_time].to_datetime + 1.hours).to_s %>
              <%= form.hidden_field :first_user_id, value: params[:first_user] %>
              <%#= hidden_field_tag 'second_user_id', match.id %>
              <%= form.hidden_field :second_user_id, value: match.id %>
              <%= form.submit "Set up a meeting", :class => 'btn btn-success'%>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

<% end %>


<%= link_to "Back to slots", slots_path %>

app/views/meetings/show.html.erb
<%= link_to "Back to meetings", meetings_path, class: "link-secondary" %>

<h2 class="my-2">Meeting Details</h2>
<div class="d-flex flex-column flex-md-row justify-content-between">

  <div class="flex-fill">
    <%= render @meeting %>

    <div>
      <%= button_to "Destroy this meeting", @meeting, method: :delete, class: "btn btn-danger my-2" %>
    </div>
  </div>

  <div class="flex-fill mb-4">
    <h5>Chat Room</h5>
    <div class="d-flex flex-column bg-light border border-dark px-2 py-2" style="max-width:400px;">

      <div class="mt-4">
        <%= render @meeting.messages %>
      </div>
      <div>
        <%= form_for([@meeting, @meeting.messages.new]) do |form| %>

            <%= form.hidden_field :sender, value: Current.user.first_name %>
            <div class="form-floating mb-3">
              <%= form.text_field :content, class: "form-control", placeholder: "Enter your message here", id: "Messagefloat" %>
              <%= form.label :content, class: "form-label", for: "Messagefloat" %>
            </div>

          <span>
            <%= form.submit "Send", class: "btn btn-success"%>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>