config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  post '/api', to: 'api_keys#create'
  delete '/api', to: 'api_keys#destroy'
  get '/api', to: 'api_keys#index'

  get '/api/user', to: 'api_keys#user_details'
  get '/api/time_slots', to: 'api_keys#time_slots'
  get '/api/meetings', to: 'api_keys#meetings'
  get '/api/meeting', to: 'api_keys#meeting'


  resources :meetings, only: [:index, :show, :new, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :slots
  root to: 'main#index'

  get 'meeting/searchDate', to: 'meetings#searchDate', as: :search_date
  # GET /about
  get 'about', to: 'about#index'

  get 'profile', to: 'profiles#edit', as: :edit_profile
  patch 'profile', to: 'profiles#update'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  # get 'user/photos', to: 'photos#index'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

end

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<%end %>

<% if flash[:alert]%>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<%end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Study Buddy", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Schedule", slots_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Meeting", meetings_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"  %>
        </li>
      </ul>



      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_profile_path, class: "nav-link" %>
          </li>
          <!--          <li class="nav-item">-->
          <%#= image_tag Current.user.avatar.variant(resize: "50x50")%>
          <!--          </li>-->
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>